apiVersion: apps/v1
kind: Deployment
metadata:
  name: azure-devops-agent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: azure-devops-agent
  template:
    metadata:
      labels:
        app: azure-devops-agent
    spec:
      containers:
      - name: azure-devops-agent
        image: furkanakgun/azure-agent-image:v3
        securityContext:
          privileged: true
        env:
        - name: AZP_URL
          valueFrom:
            secretKeyRef:
              name: azure-devops
              key: AZP_URL
        - name: AZP_TOKEN
          valueFrom:
            secretKeyRef:
              name: azure-devops
              key: AZP_TOKEN
        volumeMounts:
        - mountPath: /var/run/docker.sock
          name: docker-volume
      volumes:
      - name: docker-volume
        hostPath:
          path: /var/run/docker.sock
